config/routes.rb
Rails.application.routes.draw do
  post 'create_response/:event_id', to: 'responses#create'
  resources :contacts
  resources :organizations
  resources :events
  resources :users , only: [:new, :create]
  get 'login', to: 'sessions#new'
  post 'login', to:'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'welcome',to:'sessions#welcome'
  get 'signup', to: 'users#new'
  get 'contact', to: 'contacts#new'
  get 'home', to: 'home#index'
  get 'organization/:id', to: 'organizations#show'
  get 'create_event', to: 'events#new'
  post 'create_event', to: 'events#create'
  get 'event/:id', to: 'event#show'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => 'sessions#welcome'
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
    @is_leader = current_user.reps_org
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)
    org_id = Organization.find_by_name(current_user.organization).id
    @organization = Organization.find_by_id(org_id)

    if @event.valid?
      @event.org_id = org_id
      @event.save
      redirect_to @event
    else
      puts @event.errors.full_messages_for(:name)
       render :new
       @event.errors.clear
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :org_id, :desc, :num_needed, :eventdate)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


  <link rel="stylesheet" href="index.css">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <title>Contact us</title>
</head>
<body>
<style>
    body {
        background-color: #346094
    }

    .center {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 30%;
    }

</style>

<nav class="navbar navbar-expand-lg navbar-light py-3" style = "background-color: #FFFFFF">
  <div class="container-fluid" style="font-size:30px">
    <a class="navbar-brand" href="#"><img src = "https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/v1448128738/cl28wyysskerya6m752m.png" style="width:40px; height:40px"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <% if logged_in?%>
          <%= link_to "Organizations", '/organizations', method: :get%>
          <%= link_to "Events", '/events', method: :get%>
          <%= link_to "Contact us", '/contacts/new', method: :get%>
          <%= link_to "Logout", '/logout', method: :delete%>
        <% else %>
          <%= link_to "Login", '/login', method: :get%>
          <%= link_to "Sign Up", '/signup', method: :get%>
          <%= link_to "Contact Us", '/contacts/new', method: :get%>
        <% end %>
      </div>
    </div>
  </div>
</nav>

<p id="notice"><%= notice %></p>

<div style="color: white; text-align: center">
<h1>Events</h1>

<table class="center">
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
  <% if !@events.blank?%>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to 'Show', event, style:"color: white; text-align: center;"%></td>
        <td><%= event.name%></td>
        <td><%= event.num_needed%></td>
        <td><%= event.eventdate%></td>
      </tr>
    <% end %>
  <% else %>
    There are no events.
  <%end%>
  </tbody>
</table>

<br>
<% if current_user.reps_org%>
<%= link_to 'New Event', new_event_path, style:"color: white;" %>
<% end %>
</div>

<footer>
  <p style = "text-align: center; color: #346094"> Team U+1F5FF </p>
</footer>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

app/views/events/new.html.erb
<!DOCTYPE html>
<html>

<head>

  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light py-3" style = "background-color: #FFFFFF">
  <div class="container-fluid" style="font-size:30px">
  <a class="navbar-brand" href="#"><img src = "https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/v1448128738/cl28wyysskerya6m752m.png" style="width:40px; height:40px"></a> 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <% if logged_in?%>
          <%= link_to "Organizations", '/organizations', method: :get%>
          <%= link_to "Events", '/events', method: :get%>
          <%= link_to "Contact us", '/contacts/new', method: :get%>
          <%= link_to "Logout", '/logout', method: :delete%>
        <% else %>
          <%= link_to "Login", '/login', method: :get%>
          <%= link_to "Sign Up", '/signup', method: :get%>
          <%= link_to "Contact Us", '/contacts/new', method: :get%>
        <% end %>
      </div>
  </div>
  </div>
</nav>

<style>
body {
  background-color: #346094;
}
</style>

<h1>New Event</h1>

<div class = "container p-3 my-3 border" style = "background-color:white">

<div>

<%= form_for @event do |f|%>
  <div class="form-group" >
    <%= f.label :name, "Event Name"%><br>
    <%= f.text_field :name, {class:"form-control", placeholder:"Event Name"}%> 
    <% if @event.errors.full_messages_for(:name).any? %>
      <% @event.errors.full_messages_for(:name).each do |error| %>
        <p class="error"> <%= error %> </p>
        <% end %>
      <% end %>
    </div>

<div class="form-group" >
    <%= f.label :desc, "Event Information"%><br>
    <%= f.text_area :desc,{class:"form-control", rows:10, placeholder:"Event Name"}%>
    <% if @event.errors.full_messages_for(:desc).any? %>
    <% @event.errors.full_messages_for(:desc).each do |error| %>
        <p class="error"> <%= error %> </p>
    <% end %>
    <% end %>
</div>

  <div class="form-group" >
    <%= f.label :num_needed, "Number of Volunteers Needed"%><br>
      <%= f.number_field :num_needed, min: 1, step: 1%>
      <% if @event.errors.full_messages_for(:num_needed).any? %>
      <% @event.errors.full_messages_for(:num_needed).each do |error| %>
          <p class="error"> <%= error %> </p>
      <% end %>
      <% end %>
  <div>

  <div class="form-group" >
    <%= f.label :eventdate, "Date and Time of Event"%><br>
      <%= f.datetime_select :eventdate%>
      <% if @event.errors.full_messages_for(:eventdate).any? %>
      <% @event.errors.full_messages_for(:eventdate).each do |error| %>
          <p class="error"> <%= error %> </p>
      <% end %>
      <% end %>
  <div>


  <div class="field">
    <%= f.submit "Submit", {class:"btn btn-default"}%>
  </div>
<%end%>
</div>

</script>

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</div>

app/views/events/show.html.erb
<!doctype html>
<html lang="en">
  <head>

  	<style>
  	p2{
  		color: white;
  	}
    p, h1, h2, table {
  color:white;
}
  	</style>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">



    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>
  <body style="background-color:#346094">

  	<nav class="navbar navbar-expand-lg navbar-light py-3" style = "background-color: #FFFFFF">
  <div class="container-fluid" style="font-size:30px">
  <a class="navbar-brand" href="#"><img src = "https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/v1448128738/cl28wyysskerya6m752m.png" style="width:40px; height:40px"></a> 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <% if logged_in?%>
          <%= link_to "Organizations", '/organizations', method: :get%>
          <%= link_to "Events", '/events', method: :get%>
          <%= link_to "Contact us", '/contacts/new', method: :get%>
          <%= link_to "Logout", '/logout', method: :delete%>
        <% else %>
          <%= link_to "Login", '/login', method: :get%>
          <%= link_to "Sign Up", '/signup', method: :get%>
          <%= link_to "Contact Us", '/contacts/new', method: :get%>
        <% end %>
      </div>
  </div>
  </div>
</nav>

<p id="notice"><%= notice %></p>

<h2><%= @event.name %></h2>
<p style="style:white;">
<%= @event.desc%>
<%= @event.num_needed%>
<%= @event.eventdate%>
</p>

<% if !current_user.reps_org%>
<div>
<%= button_to "Respond", {:controller => "responses", :action => "create", :event_id => @event.id}, :method => :post%>
</div>
<% end %>

<footer>
  <p style = "text-align: center; color: #346094"> Team U+1F5FF </p>
</footer>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>