config/routes.rb
Rails.application.routes.draw do
  post 'create_response/:event_id', to: 'responses#create'
  resources :contacts
  resources :organizations
  resources :events
  resources :users , only: [:new, :create]
  get 'login', to: 'sessions#new'
  post 'login', to:'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'welcome',to:'sessions#welcome'
  get 'signup', to: 'users#new'
  get 'contact', to: 'contacts#new'
  get 'home', to: 'home#index'
  get 'organization/:id', to: 'organizations#show'
  get 'create_event', to: 'events#new'
  post 'create_event', to: 'events#create'
  get 'event/:id', to: 'event#show'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => 'sessions#welcome'
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authorized
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    # redirect_to '/contacts/new'
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: "Help request was successfully submitted." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:subject, :message)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="color: white">
    <%= form.label :Name %>
    <%= form.text_field :Name %>
  </div>

  <div class="field" style="color: white">
    <%= form.label :Email %>
    <%= form.text_field :Email %>
  </div>


  <div class="field" style="color: white">
    <%= form.label :Subject %>
    <%= form.text_field :Subject %>
  </div>

  <div class="field" style="color: white">
    <%= form.label :Message %>
    <%= form.text_field :Message %>
  </div>

  <div class="actions">
    <%= form.submit "Submit" %>
  </div>
<% end %>

app/views/contacts/contact_us.html.erb
<h1> Contact us </h1>
<p> Need assistance? </p>
<p> Call 1-877-On Your Side (1-877-669-6877) or fill out the form below </p>

<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%#= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.subject %></td>
        <td><%= contact.message %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


  <link rel="stylesheet" href="index.css">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <title>Contact us</title>
</head>
<body>
<style>
  body {
      background-color: #346094
  }

  .center {
      display: block;
      margin-left: auto;
      margin-right: auto;
      width: 30%;
  }

</style>

<nav class="navbar navbar-expand-lg navbar-light py-3" style = "background-color: #FFFFFF">
  <div class="container-fluid" style="font-size:30px">
    <a class="navbar-brand" href="#"><img src = "https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/v1448128738/cl28wyysskerya6m752m.png" style="width:40px; height:40px"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <% if logged_in?%>
          <%= link_to "Organizations", '/organizations', method: :get%>
          <%= link_to "Events", '/events', method: :get%>
          <%= link_to "Contact us", '/contacts/new', method: :get%>
          <%= link_to "Logout", '/logout', method: :delete%>
        <% else %>
          <%= link_to "Login", '/login', method: :get%>
          <%= link_to "Sign Up", '/signup', method: :get%>
          <%= link_to "Contact Us", '/contacts/new', method: :get%>
        <% end %>
      </div>
    </div>
  </div>
</nav>

<br>
<h1 style="color: white; text-align: center; font-size: 60px"> Contact us </h1>
<br>
<p style="font-size: medium; color: #fff; text-align: center; font-size: 30px"> Need assistance? </p>
<br>
<p style="color: white; font-size: medium; text-align: center; font-size: 30px"> Call 1-877-On Your Side (1-877-669-6877) or fill out the form below </p>
<br>
<div style="text-align: center">
  <%= render 'form', contact: @contact%>
</div>

<img src="https://cdn.discordapp.com/attachments/865245328084697118/865431288047337482/unknown.png" class="center">

<footer>
  <p style = "text-align: center; color: #346094"> Team U+1F5FF </p>
</footer>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<h1> Contact us </h1>
<p> Need assistance? </p>
<p> Call 1-877-On Your Side (1-877-669-6877) or fill out the form below </p>


<p>
  <strong>Subject:</strong>
  <%= @contact.subject %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<%= link_to 'Edit message', edit_contact_path(@contact) %> |
<%= link_to 'Back to homepage', welcome_path %>